# Generated by Django 3.1.3 on 2020-11-27 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 3, 38, 22, 695510, tzinfo=utc), verbose_name='date created')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 3, 38, 22, 916522, tzinfo=utc), verbose_name='date published')),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 3, 38, 22, 916522, tzinfo=utc), verbose_name='last modified')),
                ('author', models.CharField(max_length=250, verbose_name='author')),
                ('content', models.TextField(verbose_name='content')),
                ('comment_count', models.IntegerField(blank=True, default=0, verbose_name='comment count')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 3, 38, 22, 920523, tzinfo=utc), verbose_name='comment date')),
                ('author', models.CharField(default='anonymous', max_length=250, verbose_name='author name')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
