# Generated by Django 3.1.3 on 2020-11-27 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 4, 43, 31, 690020, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 4, 43, 31, 917291, tzinfo=utc), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='comment count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 4, 43, 31, 913292, tzinfo=utc), verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 4, 43, 31, 913292, tzinfo=utc), verbose_name='date published'),
        ),
    ]
